// <auto-generated />
using InsuranceCoverageBrowser.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InsuranceCoverageBrowser.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InsuranceCoverageBrowser.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Clothing"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Kitchen"
                        });
                });

            modelBuilder.Entity("InsuranceCoverageBrowser.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Name = "TV",
                            Price = 2000m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Name = "Playstation",
                            Price = 400m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Name = "Stereo",
                            Price = 1600m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Name = "Shirts",
                            Price = 1100m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Name = "Jeans",
                            Price = 1100m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            Name = "Pots and Pans",
                            Price = 3000m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            Name = "Flatware",
                            Price = 500m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            Name = "Knife Set",
                            Price = 500m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            Name = "Misc",
                            Price = 1000m
                        });
                });

            modelBuilder.Entity("InsuranceCoverageBrowser.Models.Item", b =>
                {
                    b.HasOne("InsuranceCoverageBrowser.Models.Category", "Category")
                        .WithMany("Items")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("InsuranceCoverageBrowser.Models.Category", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
